- 
    id: trips
    name: trips_ingestion
    application: /usr/local/spark/app/trips/trips_ingestion.py
    conn: spark_default
    spark_master: spark://spark:7077
    file_path: /usr/local/spark/resources/data/trips.csv
    table: trips_raw
