-
    name: trips
    application: /usr/local/spark/app/trips/table_trips.py
    conn: spark_default
    spark_master: spark://spark:7077
-
    name: region
    application: /usr/local/spark/app/trips/table_regions.py
    conn: spark_default
    spark_master: spark://spark:7077

-
    name: source
    application: /usr/local/spark/app/trips/table_source.py
    conn: spark_default
    spark_master: spark://spark:7077
